name: applocale
description: A Flutter plugin to enable support for internationalization (i18n) or different language with json files.
version: 1.0.3
homepage: https://github.com/Terran-Source/applocale
repository: https://github.com/Terran-Source/applocale
issue_tracker: https://github.com/Terran-Source/applocale/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  extend: ^0.1.1

  flutter:
    sdk: flutter
  interpolation: ^2.1.2
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
